version: '3.8'

services:
  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"  # Main edge service port
      - "4571:4571"  # Lambda API port
    environment:
      - SERVICES=s3,lambda
      - EDGE_PORT=4566
      - AWS_DEFAULT_REGION=us-east-1
      - DEBUG=1
    volumes:
      - "./localstack:/var/lib/localstack"

  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
